-- Reset: Drop existing tables if they exist (to apply changes)
drop table if exists subtasks;
drop table if exists tasks;
drop table if exists connections;
drop table if exists profiles;
-- Drop function if exists
drop function if exists generate_friend_code;

-- Create a function to generate a random 6-character alphanumeric code
create or replace function generate_friend_code()
returns text
language plpgsql
as $$
declare
  chars text[] := '{A,B,C,D,E,F,G,H,J,K,L,M,N,P,Q,R,S,T,U,V,W,X,Y,Z,2,3,4,5,6,7,8,9}';
  result text := '';
  i integer := 0;
begin
  for i in 1..6 loop
    result := result || chars[1+floor(random()*array_length(chars, 1))];
  end loop;
  return result;
end;
$$;

-- Create a table for user profiles (links to Supabase Auth)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  first_name text,
  last_name text,
  role text check (role in ('supervisor', 'janitor')),
  -- Auto-generate friend code using the function
  friend_code text unique default generate_friend_code()
);

-- Establish relationships between Supervisors and Janitors
create table connections (
  id bigint generated by default as identity primary key,
  supervisor_id uuid references profiles(id) not null,
  janitor_id uuid references profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(supervisor_id, janitor_id) -- Prevent duplicate connections
);

-- Tasks table
create table tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  is_completed boolean default false,
  assigned_to uuid references profiles(id),
  created_by uuid references profiles(id)
);

-- Subtasks table
create table subtasks (
  id bigint generated by default as identity primary key,
  task_id bigint references tasks(id) on delete cascade,
  title text not null,
  is_completed boolean default false
);
